import type { NextPage } from 'next'
import Head from 'next/head'
import {
  CarouselStyled,
  NavBarStyled,
  AnnouncementCardStyled,
  FooterStyled,
  MainInfoStyled,
  SectionStyled,
  MainGridStyled,
} from '../components'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBarStyled />
      <main>
        <MainInfoStyled />

        <SectionStyled sectionName="Classificados">
          <MainGridStyled />
        </SectionStyled>

        <SectionStyled sectionName="Depoimentos">
          <CarouselStyled />
        </SectionStyled>
      </main>

      <FooterStyled />
    </div>
  )
}

export default Home
